# https://travis-ci.org/scm-spain/slippin-jimmy
language: python
python:
- 2.7

addons:
  apt:
    packages:
    - freetds-dev



before_install:
  - sudo apt-get install libaio1
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda install --yes oracle-instantclient
install:
  - pip install -r requirements-test.txt

script: make test
